#!/usr/bin/env bash
# Uses while-loop to display "Best School" 10 times
# On the 9th iteration, displays "Hi" before "Best School".


i=1
while [ $i -le 10 ]; do
 echo "Best School"
 ((i++))
if [$i -eq 9 ]; then
echo "Hi"
fi
done

