#!/usr/bin/env bash
# why you no love me?

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command";  rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; echo "Exiting..."; exit 0' SIGQUIT

while true; do
echo "To infinity and beyond"
sleep 1
done
