#!/usr/bin/env bash
# manages manage_my_process

case "$1" in
  start)
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo 'manage_my_process started'
    ;;
  stop)
    kill "$(cat /var/run/my_process.pid)"
    rm -f manage_my_process
    echo "manage_my_process stopped"
    ;;
  restart)
    kill "$(cat /var/run/my_process.pid)"
    rm -f manage_my_process
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process_restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

