#!/usr/bin/env bash
# Find the process ID of the process named '7-highlander'

pid=$(pgrep 7-highlander)

# Check if the process is running
if [ -z "$pid" ]; then
    echo "No process named '7-highlander' found."
    exit 1
fi

# Kill the process
echo "Killing process with PID: $pid"
kill -15 $pid 

echo "Process '7-highlander' terminated."

